services:
  mahai:
    container_name: mahai
    build:
      context: .
      dockerfile: ./mahai/Dockerfile
    ports:
      - '6767:6767'
    restart: always
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./front/Dockerfile
    environment:
      PORT: 3030
    ports:
      - '3030:3030'
    restart: always
