create table "public"."Translations" (
    "id" bigint generated by default as identity not null,
    "timestampStart" text,
    "timestampEnd" text,
    "image" text,
    "translation" text,
    "video" text
);


CREATE UNIQUE INDEX "Organiztion_id_key" ON public."Translations" USING btree (id);

CREATE UNIQUE INDEX "Organiztion_pkey" ON public."Translations" USING btree (id);

alter table "public"."Translations" add constraint "Organiztion_pkey" PRIMARY KEY using index "Organiztion_pkey";

alter table "public"."Translations" add constraint "Organiztion_id_key" UNIQUE using index "Organiztion_id_key";


